---
# Source: pull-secret-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pull-secret-operator
  labels:
    app.kubernetes.io/name: pull-secret-operator
---
# Source: pull-secret-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pull-secret-operator-read
  labels:
    app.kubernetes.io/name: pull-secret-operator
rules:
  - apiGroups:
      - vsix.me
    resources:
      - pullsecrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - '*'
---
# Source: pull-secret-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pull-secret-operator-read-binding
  labels:
    app.kubernetes.io/name: pull-secret-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pull-secret-operator-read
subjects:
  - kind: ServiceAccount
    name: pull-secret-operator
    namespace: default
---
# Source: pull-secret-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pull-secret-operator
  labels:
    app.kubernetes.io/name: pull-secret-operator
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: pull-secret-operator
---
# Source: pull-secret-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pull-secret-operator
  labels:
    app.kubernetes.io/name: pull-secret-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pull-secret-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pull-secret-operator
    spec:
      serviceAccountName: pull-secret-operator
      securityContext: {}
      containers:
        - name: pull-secret-operator
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "docker.io/petergrace/pull-secret-operator:0.1.9"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
---
# Source: pull-secret-operator/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "pull-secret-operator-test-connection"
  labels:
    app.kubernetes.io/name: pull-secret-operator
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['pull-secret-operator:80']
  restartPolicy: Never
