---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Optionally uncomment to make release unique.
# prefix: release-name-

# Override the default cluster image version.
images:
  - name: "docker.io/petergrace/pull-secret-operator"
    newTag: "0.1.9"

resources:
  - deployment.yaml
