apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pullsecrets.vsix.me
spec:
  group: vsix.me
  names:
    kind: PullSecret
    plural: pullsecrets
    shortNames: []
    singular: pullsecret
  scope: Cluster
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: A PullSecret
        properties:
          apiVersion:
            description: The version of PSS
            type: string
          spec:
            description: the PullSecretSpec
            type: object
            properties:
              source:
                description: The secret to watch for changes
                properties:
                  namespace:
                    description: The namespace of the source secret
                    type: string
                    nullable: false
                  name:
                    description: the name of the source secret
                    type: string
                    nullable: false
                type: object
              targetNamespaces:
                description: A list of namespaces to copy this source secret into
                items:
                  type: string
                nullable: false
                type: array
