---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pull-secret-operator.name" . }}-read
  labels:
    {{- include "pull-secret-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - vsix.me
  resources:
  - pullsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pull-secret-operator.name" . }}-read-binding
  labels:
    {{- include "pull-secret-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pull-secret-operator.name" .}}-read
subjects:
- kind: ServiceAccount
  name: {{ include "pull-secret-operator.serviceAccountName" .}}
  namespace: {{ .Release.Namespace }}
