name: Build

on:
  push:
    branches:
      - main
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Cache target folder
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            target/
          key: ${{ runner.os }}-rustbuild
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_DOCKER_USERNAME }}
          password: ${{ secrets.HUB_DOCKER_PAT }}
      - name: run makefile
        run: make gh-build
        shell: bash
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
         username: ${{ secrets.HUB_DOCKER_USERNAME }}
         password: ${{ secrets.HUB_DOCKER_PAT }}
         repository: petergrace/pull-secret-operator   
